Enhance CI workflow with deployment steps
Added deployment steps to CI workflow for Docker container.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -12,7 +12,7 @@ jobs:
             - name: Build image
               run: |
                 docker build -t ${{secrets.DOCKER_USERNAME}}/porfolio-app:${{github.run_number}} .
-                docker build -t ${{secrets.DOCKER_USERNAME}}/porfolio-app .
+                docker build -t ${{secrets.DOCKER_USERNAME/portfolio-app.
                 
             - name: Docker Login
               uses: docker/login-action@v4
@@ -24,3 +24,18 @@ jobs:
               run: |
                 docker push ${{secrets.DOCKER_USERNAME}}/porfolio-app:${{github.run_number}}
                 docker push ${{secrets.DOCKER_USERNAME}}/porfolio-app
+
+        deploy:
+            needs: build
+            runs-on: ubuntu-latest
+            steps:
+              - name: SSH to Linux and run a container
+                uses: appleboy/ssh-action@v1
+                with:
+                  host: ${{ secrets.HOST }}
+                  username: ${{ secrets.SSH_USERNAME }}
+                  key: ${{ secrets.PRIVATE_KEY }}
+              script: |
+                  docker rm -f portfolio || echo "Container not found, skipping removal."
+                  docker rmi -f ${{secrets.DOCKER_USERNAME}}/ciportofolio || echo "image do not exist"
+                  docker run -d --name portfolio -p 8080:80 ${{secrets.DOCKER_USERNAME}}/ciportofolio
